### PR TITLE
BC-1610 - add selection by deploy stage

### PR DESCRIPTION
**Pull request by mamutmk5**
# Description
add selection by deploy stage

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-1610

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Review by BlexToGo — COMMENTED** [review]
Looks good, but can we test this change by using "infra" as a parameter to deploy to infra-schulcloud-01 and infra-schulcloud-02?

**Comment by mamutmk5** [comment]
> Looks good, but can we test this change by using "infra" as a parameter to deploy to infra-schulcloud-01 and infra-schulcloud-02?

So now we can after merging #217 to main and rebase this branch.
see for it https://github.com/hpi-schul-cloud/dof_app_deploy/blob/BC-1610/.github/workflows/rollout.yml#L247 and https://github.com/hpi-schul-cloud/dof_app_deploy/blob/BC-1610/.github/workflows/rollout.yml#L262 both are now calls for lokal workflows.

**Comment by mamutmk5** [comment]
> Looks good, but can we test this change by using "infra" as a parameter to deploy to infra-schulcloud-01 and infra-schulcloud-02?

see https://github.com/hpi-schul-cloud/dof_app_deploy/actions/runs/2100756749 there happend nothing to the other instances.

**Review by BlexToGo — APPROVED** [review]
[infra-schulcloud-01](https://infra.schulcloud-01.dbildungscloud.dev/) and [infra-schulcloud-02](https://infra.schulcloud-02.dbildungscloud.dev/) have been successfully deployed by supplying the "infra" parameter and, as expected, these were the only ones.

**Pull request merged**
